# Generated by Django 6.0 on 2026-03-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceUriCheqMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_uri', models.URLField()),
                ('CHEQ', models.JSONField()),
            ],
        ),
    ]
